wrote another yaml with multiple events

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -17,10 +17,10 @@ jobs:
   echo-goodbye:
     runs-on: ubuntu-latest
     steps:
-      - name: Failed step
-        run: |
-          "echo I will fail"
-          exit 1
+      # - name: Failed step
+      #   run: |
+      #     "echo I will fail"
+      #     exit 1
       - name: Successful step
         run: echo "I will succeed"
       - name: Say Goodbye
